#This file was generated by MC-Build

tellraw @a ["§2[dragonai - INFO]: §r",["Old Combat Datapack detected. I recommend the use of the Customizable Dragon AI 1.8 Preset for the old dragon fight experience. Switching to the preset now."]]
schedule function dragonai:presets/1.8-recommend 1t replace