#This file was generated by MC-Build

execute if entity @s[type=!ender_dragon] run return 0
scoreboard players set @s DragonChargeTimer 4
execute at @s store result score @s ChargeTargetX run data get entity @e[limit=1,sort=nearest,tag=validdragontarget] Pos[0] 100
execute at @s store result score @s ChargeTargetY run data get entity @e[limit=1,sort=nearest,tag=validdragontarget] Pos[1] 100
execute at @s store result score @s ChargeTargetZ run data get entity @e[limit=1,sort=nearest,tag=validdragontarget] Pos[2] 100