#This file was generated by MC-Build

# 1.9-1.13.2 preset
# Run on pack load
scoreboard players set Allow1.9Behavior DragonAISettings 1
scoreboard players set ReplaceVanillaCharging DragonAISettings 0
scoreboard players set MiscDragonTweaks DragonAISettings 1
scoreboard players set FrequentPerching DragonAISettings 0
scoreboard players set DragonCharging DragonAISettings 0
scoreboard players set BedrockStyle DragonAISettings 0
scoreboard players set FlySpeed DragonAISettings 900
scoreboard players set ChargeFlySpeed DragonAISettings 100
scoreboard players set VerticalSmoothing DragonAISettings 50
scoreboard players set HorizontalSmoothing DragonAISettings 50
scoreboard players set Slowdown DragonAISettings 15
scoreboard players set MimicVanillaCharging DragonAISettings 1
scoreboard players set UseEnhancedAI DragonAISettings 0