#This file was generated by MC-Build

# Allow both the vanilla behavior and the mechanics added in this datapack to coexist
scoreboard players set Allow1.9Behavior DragonAISettings 1
scoreboard players set ReplaceVanillaCharging DragonAISettings 0
scoreboard players set FixVertical DragonAISettings 1
scoreboard players set FrequentPerching DragonAISettings 1
scoreboard players set ChargeRate DragonAISettings 5
scoreboard players set DragonCharging DragonAISettings 1
scoreboard players set BedrockStyle DragonAISettings 1
scoreboard players set FlySpeed DragonAISettings 1900
scoreboard players set ChargeFlySpeed DragonAISettings 200
scoreboard players set VerticalSmoothing DragonAISettings 50
scoreboard players set HorizontalSmoothing DragonAISettings 50
scoreboard players set Slowdown DragonAISettings 15
scoreboard players set MimicVanillaCharging DragonAISettings 0
scoreboard players set StopChargeOnHurt DragonAISettings 1
# function dragonai:config
execute unless score Enabled DragonAISettings matches 1 run function dragonai:logging/disabled_warning