#This file was generated by MC-Build

tellraw @a ["§6[dragonai - WARN]: ","§6The tag '#dragonai:dragon_charge_at' has been detected to include players, this will cause the dragon to charge at players in ALL GAMEMODES, not just survival and adventure. By default the pack will allow dragons to charge at players in survival and adventure, so adding players to the tag isn't needed."]