#This file was generated by MC-Build

# execute store result score @s Rotation run data get entity @s Rotation[0] 100
scoreboard players set ST Temp 2000
scoreboard players set B Temp 1000
scoreboard players set F Temp 1150
scoreboard players set WR Temp 500
scoreboard players set 100 Temp 100
execute if score EnableDebug DragonAISettings matches 1 at @s run particle minecraft:campfire_signal_smoke ~ ~ ~ 0 0 0 0 2 force
execute if score EnableDebug DragonAISettings matches 1 at @s rotated ~ 0 run particle minecraft:campfire_cosy_smoke ^ ^ ^-10 0 0 0 0 0 force
execute store result entity @e[type=marker,limit=1,sort=nearest,tag=DragonChargeRotation] Rotation[0] float 0.01 run scoreboard players get @s Rotation
execute at @e[type=marker,limit=1,sort=nearest,tag=DragonChargeRotation] rotated ~90 0 run summon marker ^ ^ ^-1 {Tags:["SmoothTurn","Right","Far"]}
execute at @e[type=marker,limit=1,sort=nearest,tag=DragonChargeRotation] rotated ~8 0 run summon marker ^ ^ ^-1 {Tags:["SmoothTurn","Right"]}
execute at @e[type=marker,limit=1,sort=nearest,tag=DragonChargeRotation] rotated ~0 0 run summon marker ^ ^ ^-1 {Tags:["SmoothTurn","NoTurn"]}
execute at @e[type=marker,limit=1,sort=nearest,tag=DragonChargeRotation] rotated ~-8 0 run summon marker ^ ^ ^-1 {Tags:["SmoothTurn","Left"]}
execute at @e[type=marker,limit=1,sort=nearest,tag=DragonChargeRotation] rotated ~-90 0 run summon marker ^ ^ ^-1 {Tags:["SmoothTurn","Left","Far"]}
# execute at @e[type=marker,limit=1,sort=nearest,tag=DragonChargeRotation] rotated ~-180 0 run summon marker ^ ^ ^-1 {Tags:["SmoothTurn","Behind"]}
execute if score EnableDebug DragonAISettings matches 1 as @e[tag=SmoothTurn,type=marker] at @s run particle electric_spark ~ ~0.5 ~ 0 0 0 0 0 force
execute at @s as @e[tag=DragonChargeTarget,limit=1,sort=nearest] at @s run tag @e[tag=SmoothTurn,type=marker,limit=1,sort=nearest] add Closest
execute at @s as @e[tag=DragonChargeRotation,type=marker,limit=1,sort=nearest] facing entity @e[tag=DragonChargeTarget] feet rotated ~ ~ run tp @s ^ ^ ^ ~180 ~
execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=Right,tag=Far] at @s run scoreboard players add @s RVel 125
execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=Right] at @s run scoreboard players add @s RVel 125
execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=Left] at @s run scoreboard players remove @s RVel 125
execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=Left,tag=Far] at @s run scoreboard players remove @s RVel 125
execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=Behind] at @s if score @s RVel matches 0 run scoreboard players add @s RVel 10
execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=Behind] at @s if score @s RVel matches 1.. run scoreboard players operation @s RVel += WR Temp
execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=Behind] at @s if score @s RVel matches ..-1 run scoreboard players operation @s RVel -= WR Temp
# execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=Behind] at @s run scoreboard players operation @s RVel /= 100 Temp
scoreboard players operation @s RVel *= B Temp
scoreboard players operation @s RVel /= F Temp
execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=NoTurn] at @s store result score @s Rotation run data get entity @e[limit=1,tag=DragonChargeRotation,sort=nearest] Rotation[0] 100
# execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=NoTurn] at @s run scoreboard players operation @s RVel *= B Temp
# execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=NoTurn] at @s run scoreboard players operation @s RVel /= ST Temp
execute if entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=NoTurn] at @s run scoreboard players set @s RVel 0
execute unless entity @e[type=marker,tag=SmoothTurn,tag=Closest,tag=NoTurn] run scoreboard players operation @s Rotation += @s RVel
execute store result entity @s Rotation[0] float 0.01 run scoreboard players get @s Rotation
kill @e[tag=SmoothTurn,type=marker]
tag @e remove Closest