#This file was generated by MC-Build

execute store success score HasOldCombat Temp run scoreboard objectives setdisplay sidebar.team.yellow OldCombatSettings
execute if score HasOldCombat Temp matches 1 run function dragonai:misc/zzz/0
scoreboard objectives setdisplay sidebar.team.yellow