#This file was generated by MC-Build

scoreboard players set #ifelse mcb.internal 1
execute if score FrequentPerching DragonAISettings matches 1 run function dragonai:config/zzz/16
execute if score FrequentPerching DragonAISettings matches 0 run function dragonai:config/zzz/17