#This file was generated by MC-Build

tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
$tellraw @s ["$(namespace) is asking if you're sure about this action."]
tellraw @s ""
$tellraw @s ["",{"text":"[Confirm]","color":"green","clickEvent":{"action":"run_command","value":'function z_configmenu:run_and_return {cmd:\'$(yes)\',return:\'function $(return)\'}'}}," ",{"text":"[Cancel]","color":"red","clickEvent":{"action":"run_command","value":'function z_configmenu:run_and_return {cmd:\'$(no)\',return:\'function $(return)\'}'}}]
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""
tellraw @s ""