#This file was generated by MC-Build

tellraw @s [{text:"[Test Confirmation]",click_event:{action:run_command,command:"function z_configmenu:confirm {yes:'tellraw @s \"Yes\"',no:'tellraw @s \"No\"',return:'function z_configmenu:testconfig',namespace:'z_configmenu'}"}}]